export type MenuItem = { nr?: number; name: string; description?: string; price: string };
export type MenuCategory = { id: string; name: string; italian: string; items: MenuItem[] };

export const menuCategories: MenuCategory[] = [
  { id: "pizza", name: "Pizza", italian: "Le Pizze Rosse", items: [
    { nr: 1, name: "Pizza Semplice", description: "mit Tomaten und Käse", price: "9,50 €" },
    { nr: 2, name: "Pizza Margherita", description: "mit Tomaten, Mozzarella, Basilikum und nativem Olivenöl", price: "10,50 €" },
    { nr: 3, name: "Pizza San Marco", description: "mit Tomaten, Käse und Salami", price: "10,50 €" },
    { nr: 4, name: "Pizza Vulcano", description: "mit Tomaten, Käse und Peperoniwurst", price: "10,50 €" },
    { nr: 5, name: "Pizza Giuliana", description: "mit Tomaten, Käse und Champignons", price: "10,50 €" },
    { nr: 6, name: "Pizza Casablanca", description: "mit Tomaten, Käse und Schinken", price: "10,50 €" },
    { nr: 7, name: "Pizza Capricciosa", description: "mit Tomatensauce, Käse, Schinken, Champignons, Oliven und Artischocken", price: "12,50 €" },
    { nr: 8, name: "Pizza Pugliese", description: "mit Tomatensauce, Käse, Salami und Schinken", price: "11,50 €" },
    { nr: 9, name: "Pizza Rustica", description: "mit Tomatensauce, Käse, Schinken und Champignons", price: "11,50 €" },
    { nr: 10, name: "Pizza Casanova", description: "mit Tomatensauce, Käse, Artischocken, Oliven, Knoblauch und Petersilie", price: "11,50 €" },
    { nr: 11, name: "Pizza Boney M", description: "mit Tomatensauce, Käse, Thunfisch und Zwiebeln", price: "12,50 €" },
    { nr: 12, name: "Pizza Quattro Fogli", description: "mit Tomatensauce, Käse, Salami, Schinken, Champignons, Oliven und Artischocken", price: "13,50 €" },
    { nr: 13, name: "Pizza Calzone", description: "mit Tomatensauce, Käse, Schinken, Salami, Zwiebeln, Paprika, Oliven und Artischocken", price: "13,50 €" },
    { nr: 14, name: "Pizza Frutti di Mare", description: "mit Tomatensauce, Käse, Meeresfrüchten, Oliven, nativem Olivenöl und frischen Kräutern", price: "13,50 €" },
    { nr: 15, name: "Pizza Vegetaria", description: "mit Tomatensauce, Käse und verschiedenem Gemüse", price: "13,50 €" },
    { nr: 16, name: "Pizza L’Antica Sicilia", description: "mit Allem", price: "14,50 €" },
    { nr: 17, name: "Pizza Calzone UFO", description: "gefüllt mit Tomatensauce, Mozzarella, Schinken und Spinat", price: "13,50 €" },
    { nr: 18, name: "Pizza Popeye", description: "mit Tomatensauce, Käse, Spinat, Knoblauch und Oliven", price: "12,50 €" },
    { nr: 19, name: "Pizza Parma Rucola", description: "mit Tomatensauce, Mozzarella, Parmaschinken, Rucola, Parmesansplittern und nativem Olivenöl", price: "14,00 €" },
    { nr: 20, name: "Pizza U.S.A.", description: "mit Hackfleischsauce, Käse, Peperoniwurst und Zwiebeln", price: "13,50 €" },
    { nr: 21, name: "Pizza Palermo", description: "mit Tomatensauce, Mozzarella, Sardellen, Oliven, Kapern und frischem Basilikum", price: "12,50 €" },
    { nr: 22, name: "Pizza alla Parmigiana", description: "mit Tomatensauce, Käse, Aubergine, Parmesan und frischem Basilikum", price: "13,50 €" },
    { nr: 23, name: "Pizza Bruschetta", description: "mit Tomatensauce, Cocktailtomaten, Rucola, Parmesansplittern und nativem Olivenöl", price: "12,50 €" },
    { nr: 24, name: "Pizza Quattro Formaggi", description: "mit Tomatensauce und vier verschiedenen Käsesorten", price: "12,50 €" },
    { nr: 25, name: "Pizza Regina", description: "mit Tomatensauce, frischen Tomaten, Mozzarella, Basilikum und nativem Olivenöl", price: "12,50 €" },
    { name: "Familien-Pizza", description: "für 6 Personen · Belag nach Wunsch", price: "auf Anfrage" },
  ] },
  { id: "bianche", name: "Pizza Bianche", italian: "Le Pizze Bianche", items: [
    { name: "Pizza La Frittella", description: "mit Sahnesauce, Mozzarella, gegrillter Zucchini, Artischocken, ital. Salsiccia und nativem Olivenöl", price: "14,50 €" },
    { name: "Pizza Pescatore", description: "mit Sahnesauce, Mozzarella, Spinat, Lachs, Oliven, Cocktailtomaten und nativem Olivenöl", price: "15,00 €" },
    { name: "Pizza Carbonara", description: "mit Sahnesauce, Mozzarella, Speck und Ei", price: "13,50 €" },
    { name: "Pizza Pesto e Salmone", description: "mit hausgemachter Basilikumsauce, Mozzarella, Cocktailtomaten und Räucherlachs", price: "15,00 €" },
    { name: "Pizza Salsiccia e Friarelli", description: "mit Sahnesauce, Mozzarella, Stängelkohl, ital. Salsiccia, Knoblauch und nativem Olivenöl", price: "14,50 €" },
    { name: "Pizza Mary", description: "mit Sahnesauce, Mozzarella, Schinken und Mais", price: "13,50 €" },
    { name: "Pizza Mortadella e Pistacchio", description: "mit Sahnesauce, Mozzarella, Mortadella, Pistaziencreme und Basilikum", price: "13,50 €" },
    { name: "Pizza Tarantella", description: "mit Sahnesauce, Mozzarella, gegrillter Zucchini, Artischocken, ital. Salsiccia und nativem Olivenöl", price: "14,50 €" },
  ] },
  { id: "pasta", name: "Nudelgerichte", italian: "La Pasta", items: [
    { name: "Napoli", description: "mit einer fruchtigen Tomatensauce und frischem Basilikum", price: "9,50 €" },
    { name: "Bolognese", description: "mit einer kräftigen Hackfleischsauce und frischen Kräutern", price: "11,50 €" },
    { name: "Aglio, Olio e Peperoncino", description: "mit frischem Knoblauch, Olivenöl und frischem Basilikum", price: "10,50 €" },
    { name: "Montecati", description: "mit einer fruchtigen Tomaten-Sahnesauce", price: "10,00 €" },
    { name: "Mexico", description: "mit einer scharfen Tomaten-Sahnesauce und Schinken", price: "11,50 €" },
    { name: "Alla Panna", description: "mit Sahnesauce und Schinken", price: "12,50 €" },
    { name: "Carbonara", description: "mit Sahnesauce, Ei und Speck", price: "12,50 €" },
    { name: "Popeye", description: "mit Sahnesauce, Gorgonzola, Spinat und Pinienkernen", price: "12,50 €" },
    { name: "Pesto", description: "mit hausgemachter Basilikumsauce, Cocktailtomaten, Rucola und Feta-Käse", price: "13,50 €" },
    { name: "Matriciana", description: "mit einer fruchtigen Tomatensauce, Zwiebeln und Speck", price: "12,50 €" },
    { name: "Francia", description: "mit Tomaten-Sahnesauce, Thunfisch und frischen Kräutern", price: "12,50 €" },
    { name: "Alla Chef", description: "mit Tomaten-Sahnesauce, Schinken, Erbsen, Paprika und Broccoli", price: "13,00 €" },
    { name: "Arrabbiata Speciale", description: "mit einer scharfen Tomatensauce, Kapern, Oliven, Sardellen, Knoblauch und frischen Kräutern", price: "12,50 €" },
    { name: "Alla Norma", description: "mit einer fruchtigen Tomatensauce, Aubergine und Mozzarella", price: "12,50 €" },
    { name: "Kickers", description: "mit einer Hackfleisch-Tomaten-Sahnesauce und frischen Kräutern", price: "12,50 €" },
    { name: "Parma", description: "mit Rucola-Balsamicosauce, Parmaschinken, Champignons und Lauchzwiebeln", price: "12,50 €" },
    { name: "Al Salmone e Spinaci", description: "mit Sahnesauce, Spinat und Lachs", price: "13,50 €" },
    { name: "Broccoli e Salmone", description: "mit Tomaten-Sahnesauce, roten Zwiebeln, Broccoli, Lachs und Cocktailtomaten", price: "13,50 €" },
    { name: "Marinara", description: "mit Meeresfrüchten, Cocktailtomaten und frischen Kräutern", price: "13,50 €" },
    { name: "Al Scampi", description: "mit gegrillten Garnelen, Zucchini, Cocktailtomaten, roten Zwiebeln und frischen Kräutern in Sahnesauce", price: "14,50 €" },
    { name: "Alla Mamma", description: "mit frischen Garnelen, Rucola und Parmesansplittern", price: "14,50 €" },
    { name: "Tonno e Verdura", description: "mit Weißwein-Sahnesauce, verschiedenem Gemüse, Thunfisch und frischen Kräutern", price: "13,50 €" },
    { name: "Maximus", description: "mit einer cremigen Sahne-Senfsauce, Hähnchenfleisch, Lauchzwiebeln und sonnengetrockneten Tomaten", price: "13,50 €" },
    { name: "Biancaneve", description: "mit Sahnesauce, Hähnchenfleisch, Champignons, Lauchzwiebeln und Zucchini", price: "13,50 €" },
    { name: "Papa Alfonso", description: "mit einer fruchtigen Tomatensauce, Broccoli, Erbsen und Hähnchenfleisch", price: "13,50 €" },
    { name: "Salsiccia e Friarelli", description: "mit Sahnesauce, ital. Salsiccia, Stängelkohl, Cocktailtomaten und Parmesan", price: "13,50 €" },
    { name: "Alla Mafiosa", description: "mit einer fruchtigen Tomatensauce, ital. Salsiccia, Parmesansplittern und frischen Kräutern", price: "13,50 €" },
    { name: "Nonna Enza", description: "mit Sahnesauce, Zucchini, ital. Salsiccia und frischen Kräutern", price: "13,50 €" },
    { name: "Pasta Mista", description: "Komposition aus drei Pasta-Arten und drei Saucen: Funghi-Pesto, Tortellini mit Sahne-Schinken-Sauce und Spaghetti Napoli", price: "27,00 €" },
  ] },
  { id: "ofen", name: "Aus dem Ofen", italian: "Al Forno", items: [
    { name: "Lasagne", description: "mit Hackfleischsauce, Béchamelsauce und Käse überbacken", price: "13,50 €" },
    { name: "Rigatoni al Forno", description: "mit Hackfleisch, Schinken, Erbsen, Champignons, Paprika und Käse überbacken", price: "13,50 €" },
    { name: "Pasticcio Siciliano", description: "mit drei verschiedenen Nudelsorten, Tomaten-Sahnesauce, Schinken, Erbsen und Käse überbacken", price: "13,50 €" },
  ] },
  { id: "fleisch", name: "Fleischgerichte", italian: "Carne", items: [
    { name: "Schnitzel Wiener Art", description: "frisch paniertes Schweineschnitzel", price: "16,50 €" },
    { name: "Jägerschnitzel", description: "frisch paniertes Schweineschnitzel mit Pilz-Rahmsauce", price: "18,50 €" },
    { name: "Pfefferschnitzel", description: "frisch paniertes Schweineschnitzel mit Pfeffer-Rahmsauce", price: "18,50 €" },
  ] },
  { id: "fisch", name: "Fischgerichte", italian: "Pesce", items: [
    { name: "Calamari alla Romana", description: "frisch panierte Calamari-Ringe mit Aioli-Sauce", price: "17,00 €" },
    { name: "Scampi L’Antica Sicilia", description: "gegrillte Scampi in Tomaten-Knoblauchsauce", price: "19,50 €" },
    { name: "Scampi alla Griglia", description: "gegrillte Scampi mit Aioli-Sauce und Zitrone", price: "19,50 €" },
  ] },
  { id: "salate", name: "Salate", italian: "Insalate", items: [
    { name: "Insalata L’Antica Sicilia", description: "frischer Blattsalat mit Tomaten, Gurken, Peperoni, Paprika, Artischocken, Karotten, Oliven, Käse, Schinken, Ei, Thunfisch und Zwiebeln", price: "12,50 €" },
    { name: "Caprese", description: "mit Tomaten, Mozzarella und Basilikum", price: "9,50 €" },
    { name: "Tomatensalat", description: "mit Tomaten, Zwiebeln, Oliven, Balsamico-Sauce, nativem Olivenöl und frischen Kräutern", price: "8,00 €" },
    { name: "Gemischter Salat", description: "frischer Blattsalat mit Tomaten, Gurken, Peperoni, Paprika, Artischocken, Karotten, Oliven, Zwiebeln und Radieschen", price: "9,50 €" },
    { name: "Parma e Rucola", description: "mit Rucola, Tomaten, Parmaschinken, Parmesansplittern und Oliven", price: "12,00 €" },
    { name: "Al Capone", description: "frischer Blattsalat mit Tomaten, Gurken, Hähnchenstreifen, Paprika, Champignons, Oliven, Rucola und Zwiebeln", price: "12,50 €" },
    { name: "Fagioli", description: "frischer Blattsalat mit Tomaten, Mais, roten Bohnen, Ei, Feta-Käse, Oliven und Zwiebeln", price: "12,50 €" },
    { name: "Insalata di Mare", description: "gemischte Meeresfrüchte mit Salatgarnitur, Oliven, Balsamico-Sauce und Zitronenscheibe", price: "12,50 €" },
  ] },
  { id: "dessert", name: "Dessert", italian: "Dolci", items: [
    { name: "Pizza Nutella", price: "7,50 €" },
    { name: "Pizza Smarties", description: "mit Nutella und Smarties", price: "8,50 €" },
    { name: "Tiramisu", price: "6,50 €" },
  ] },
  { id: "getraenke", name: "Getränke", italian: "Bevande", items: [
    { name: "Wasser", description: "still oder sprudelnd", price: "2,80 €" },
    { name: "Cola / Cola Light", price: "3,10 €" },
    { name: "Cola Zero", price: "3,10 €" },
    { name: "Fanta", price: "3,10 €" },
    { name: "Sprite / Mezzo Mix", price: "3,10 €" },
    { name: "Eistee", description: "Pfirsich oder Zitrone", price: "3,10 €" },
    { name: "Apfelschorle", price: "3,10 €" },
    { name: "Hausgemachte Limonade", description: "Limette-Minze", price: "4,80 €" },
  ] },
];

export const menuItemCount = menuCategories.reduce((sum, c) => sum + c.items.length, 0);
